name: iOS Build Workflow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: macos-latest

    steps:
      # Step 1: 检出代码
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: 设置 Node.js 环境
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Step 3: 安装 Node.js 依赖
      - name: Install Node.js dependencies
        run: |
          npm install

      # Step 4: 安装 CocoaPods 依赖
      - name: Install CocoaPods dependencies
        run: |
          gem install cocoapods
          cd ios
          pod install

      # Step 5: 构建未签名的 IPA
      - name: Build Unsigned IPA
        run: |
          xcodebuild -workspace ios/LxMusicMobile.xcworkspace \
                     -scheme LxMusicMobile \
                     -sdk iphoneos \
                     -configuration Release \
                     archive -archivePath $PWD/build/LxMusicMobile.xcarchive

          xcodebuild -exportArchive \
                     -archivePath $PWD/build/LxMusicMobile.xcarchive \
                     -exportPath $PWD/build \
                     -exportOptionsPlist ios/ExportOptions.plist

      # Step 6: 上传未签名的 IPA 文件
      - name: Upload Unsigned IPA
        uses: actions/upload-artifact@v3
        with:
          name: LxMusicMobile-unsigned.ipa
          path: build/LxMusicMobile.ipa
